name: GameStore Deploy

on:
  push:
    branches:
      - dev
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Prepare WordPress Zip
      run: |
        WP_LINK=$(cat wp-version-control.cfg)
        wget -O "./wordpress.zip" "$WP_LINK"

    - name: Prepare plugins and theme zip
      run: zip -r wpcontent.zip plugins mu-plugins themes

    - name: Copy Zips to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_SSH_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        source: "./wordpress.zip, ./wpcontent.zip"
        target: ${{ github.event_name == 'push' && '/var/www/html/dev' || '/var/www/html/live' }}

    - name: Enable Maintenance Mode
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_SSH_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        source: ".maintenance"
        target: ${{ github.event_name == 'push' && '/var/www/html/dev' || '/var/www/html/live' }}

    - name: Update WordPress Core
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_SSH_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          find "${{ github.event_name == 'push' && '/var/www/html/dev' || '/var/www/html/live' }} -name "wordpress.zip" -exec unzip -o {} -d ${{ github.event_name == 'push' && '/var/www/html/dev' || '/var/www/html/live' }}" -type f -name "*.php" ! -name "wp-config.php" -delete
          rm -r "${{ github.event_name == 'push' && '/var/www/html/dev' || '/var/www/html/live' }}/wp-admin/" "${{ github.event_name == 'push' && '/var/www/html/dev' || '/var/www/html/live' }}/wp-includes/"
          unzip -o "${{ github.event_name == 'push' && '/var/www/html/dev' || '/var/www/html/live' }}/wordpress.zip" -d  "${{ github.event_name == 'push' && '/var/www/html/dev' || '/var/www/html/live' }}/"
          mv  "${{ github.event_name == 'push' && '/var/www/html/dev' || '/var/www/html/live' }}/wordpress/*"  "${{ github.event_name == 'push' && '/var/www/html/dev' || '/var/www/html/live' }}/"
          rm -r  "${{ github.event_name == 'push' && '/var/www/html/dev' || '/var/www/html/live' }}/wordpress"

    - name: Update Plugins and Theme
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_SSH_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          rm -rf "${{ github.event_name == 'push' && '/var/www/html/dev' || '/var/www/html/live' }}/wp-content/plugins" "${{ github.event_name == 'push' && '/var/www/html/dev' || '/var/www/html/live' }}/wp-content/mu-plugins" "${{ github.event_name == 'push' && '/var/www/html/dev' || '/var/www/html/live' }}/wp-content/themes"
          unzip -o "${{ github.event_name == 'push' && '/var/www/html/dev' || '/var/www/html/live' }}/wpcontent.zip" -d "${{ github.event_name == 'push' && '/var/www/html/dev' || '/var/www/html/live' }}/wp-content/"

    - name: Disable Maintenance Mode and Remove Zips
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_SSH_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          rm -f "${{ github.event_name == 'push' && '/var/www/html/dev' || '/var/www/html/live' }}/.maintenance"
          rm -f "${{ github.event_name == 'push' && '/var/www/html/dev' || '/var/www/html/live' }}/wpcontent.zip"
          rm -f "${{ github.event_name == 'push' && '/var/www/html/dev' || '/var/www/html/live' }}/wordpress.zip"